### ISSUE TITLE
Error installing listen: ruby_dep requires Ruby version >= 2.0.0, ~> 2.0.

### ISSUE THREAD

**Issue by pawohl** [thm-projects/arsnova-vagrant#29]
In the end, I am not able to get ArsNova API? running (though tomcat is listening).

```
HTTP Status 404 - /api/configuration/
type Status report
message /api/configuration/
description The requested resource is not available.
```

Host system: OSX 10.11.4
VirtualBox: 5.0.4
Vagrant: 1.8.1

```
$ vagrant up production
Bringing machine 'production' up with 'virtualbox' provider...
==> production: Importing base box 'commana/arsnova-debian-wheezy-puppet3-amd64'...
==> production: Matching MAC address for NAT networking...
==> production: Checking if box 'commana/arsnova-debian-wheezy-puppet3-amd64' is up to date...
==> production: Setting the name of the VM: arsnova-vagrant_production_1463138051651_66064
...
==> production: Running provisioner: hosts...
==> production: Running provisioner: puppet...
==> production: Running Puppet with debian-wheezy.pp...
==> production: stdin: is not a tty
==> production: Warning: Setting manifestdir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> production:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')
==> production: 
==> production: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> production:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')
==> production: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> production: Warning: Scope(Git::Repo[arsnova-backend]): The use of the git::repo resource is depreciated. Please consider using the Puppetlabs vcsrepo class.
==> production: Warning: Scope(Git::Repo[arsnova-mobile]): The use of the git::repo resource is depreciated. Please consider using the Puppetlabs vcsrepo class.
==> production: Warning: Scope(Git::Repo[arsnova-setuptool]): The use of the git::repo resource is depreciated. Please consider using the Puppetlabs vcsrepo class.
==> production: Notice: Compiled catalog for arsnova-production in environment production in 2.13 seconds
...
==> production: Notice: /Stage[main]/Motd/File[/etc/motd]/content: content changed '{md5}9830e3dbb6a828f2cc824db8db0ceaf7' to '{md5}d555a9ae60b44ae0fd6fb239a281c5e4'
==> production: Error: Could not update: Execution of '/usr/bin/gem install --no-rdoc --no-ri listen' returned 1: Building native extensions.  This could take a while...
==> production: ERROR:  Error installing listen:
==> production: 	ruby_dep requires Ruby version >= 2.0.0, ~> 2.0.
==> production: Wrapped exception:
==> production: Execution of '/usr/bin/gem install --no-rdoc --no-ri listen' returned 1: Building native extensions.  This could take a while...
==> production: ERROR:  Error installing listen:
==> production: 	ruby_dep requires Ruby version >= 2.0.0, ~> 2.0.
==> production: Error: /Stage[main]/Arsnova/Package[listen]/ensure: change from absent to latest failed: Could not update: Execution of '/usr/bin/gem install --no-rdoc --no-ri listen' returned 1: Building native extensions.  This could take a while...
==> production: ERROR:  Error installing listen:
==> production: 	ruby_dep requires Ruby version >= 2.0.0, ~> 2.0.
==> production: Notice: /Stage[main]/Arsnova/File[/etc/apache2/httpd.conf]/ensure: defined content as '{md5}d41d8cd98f00b204e9800998ecf8427e'
```

[Full log](https://dpaste.de/XKAM)

The base image (`commana/arsnova-debian-wheezy-puppet3-amd64`) appears to be an obsolete Debian version that has no ruby 2.0.0.

**Comment by commana** [comment]
Thanks for trying out arsnova-vagrant and thanks for your feedback. You are right, the base images are obsolete. Unfortunately, this project is not under active maintenance any more. We will discuss internally how we will go forward with this project and will let you know if we are going to update the components.
